<a href="https://colab.research.google.com/github/kimc11/205data/blob/main/Myfirst_testcolabfile.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In-class, we will practice how to upload data file to google colab

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/kimc11/205data/refs/heads/main/movies_imdb.csv")
df.head()

,Unnamed: 0,director_name,duration,director_facebook_likes,actor_1_facebook_likes,gross,actor_1_name,movie_title,facenumber_in_poster,plot_keywords,language,content_rating,budget,title_year,imdb_score,movie_facebook_likes,genre
0,0,James Cameron,178.0,0.0,1000.0,760505847.0,CCH Pounder,Avatar,0.0,avatar|future|marine|native|paraplegic,English,PG-13,237000000.0,2009.0,7.9,33000,Action
1,1,Gore Verbinski,169.0,563.0,40000.0,309404152.0,Johnny Depp,Pirates of the Caribbean: At World's End,0.0,goddess|marriage ceremony|marriage proposal|pi...,English,PG-13,300000000.0,2007.0,7.1,0,Action
2,2,Sam Mendes,148.0,0.0,11000.0,200074175.0,Christoph Waltz,Spectre,1.0,bomb|espionage|sequel|spy|terrorist,English,PG-13,245000000.0,2015.0,6.8,85000,Action
3,3,Christopher Nolan,164.0,22000.0,27000.0,448130642.0,Tom Hardy,The Dark Knight Rises,0.0,deception|imprisonment|lawlessness|police offi...,English,PG-13,250000000.0,2012.0,8.5,164000,Action
4,4,Doug Walker,NaN,131.0,131.0,NaN,Doug Walker,Star Wars: Episode VII - The Force Awakens,0.0,NaN,NaN,NaN,NaN,NaN,7.1,0,Documentary

#descibe: basic statistics about the dataset

In [ ]:
df.describe()

,Unnamed: 0,duration,director_facebook_likes,actor_1_facebook_likes,gross,facenumber_in_poster,budget,title_year,imdb_score,movie_facebook_likes
count,4916.000000,4901.000000,4814.000000,4909.000000,4.054000e+03,4903.000000,4.432000e+03,4810.000000,4916.000000,4916.000000
mean,2457.500000,107.090798,691.014541,6494.488491,4.764451e+07,1.377320,3.654749e+07,2002.447609,6.437429,7348.294142
std,1419.271292,25.286015,2832.954125,15106.986884,6.737255e+07,2.023826,1.002427e+08,12.453977,1.127802,19206.016458
min,0.000000,7.000000,0.000000,0.000000,1.620000e+02,0.000000,2.180000e+02,1916.000000,1.600000,0.000000
25%,1228.750000,93.000000,7.000000,607.000000,5.019656e+06,0.000000,6.000000e+06,1999.000000,5.800000,0.000000
50%,2457.500000,103.000000,48.000000,982.000000,2.504396e+07,1.000000,1.985000e+07,2005.000000,6.600000,159.000000
75%,3686.250000,118.000000,189.750000,11000.000000,6.110841e+07,2.000000,4.300000e+07,2011.000000,7.200000,2000.000000
max,4915.000000,511.000000,23000.000000,640000.000000,7.605058e+08,43.000000,4.200000e+09,2016.000000,9.500000,349000.000000

In [ ]:
df.columns

Index(['Unnamed: 0', 'director_name', 'duration', 'director_facebook_likes',
       'actor_1_facebook_likes', 'gross', 'actor_1_name', 'movie_title',
       'facenumber_in_poster', 'plot_keywords', 'language', 'content_rating',
       'budget', 'title_year', 'imdb_score', 'movie_facebook_likes', 'genre'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=4916, step=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4916 entries, 0 to 4915
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               4916 non-null   int64
 1   director_name            4814 non-null   object
 2   duration                 4901 non-null   float64
 3   director_facebook_likes  4814 non-null   float64
 4   actor_1_facebook_likes   4909 non-null   float64
 5   gross                    4054 non-null   float64
 6   actor_1_name             4909 non-null   object
 7   movie_title              4916 non-null   object
 8   facenumber_in_poster     4903 non-null   float64
 9   plot_keywords            4764 non-null   object
 10  language                 4902 non-null   object
 11  content_rating           4616 non-null   object
 12  budget                   4432 non-null   float64
 13  title_year               4810 non-null   float64
 14  imdb_score               4916 non-null   float64
 15  movie_facebook_likes     4916 non-null   int64
 16  genre                    4916 non-null   object
dtypes: float64(8), int64(2), object(7)
memory usage: 653.0+ KB

In [ ]:
df.size

83572

In [ ]:
df.shape

(4916, 17)

In [ ]:
df.head()

,Unnamed: 0,director_name,duration,director_facebook_likes,actor_1_facebook_likes,gross,actor_1_name,movie_title,facenumber_in_poster,plot_keywords,language,content_rating,budget,title_year,imdb_score,movie_facebook_likes,genre
0,0,James Cameron,178.0,0.0,1000.0,760505847.0,CCH Pounder,Avatar,0.0,avatar|future|marine|native|paraplegic,English,PG-13,237000000.0,2009.0,7.9,33000,Action
1,1,Gore Verbinski,169.0,563.0,40000.0,309404152.0,Johnny Depp,Pirates of the Caribbean: At World's End,0.0,goddess|marriage ceremony|marriage proposal|pi...,English,PG-13,300000000.0,2007.0,7.1,0,Action
2,2,Sam Mendes,148.0,0.0,11000.0,200074175.0,Christoph Waltz,Spectre,1.0,bomb|espionage|sequel|spy|terrorist,English,PG-13,245000000.0,2015.0,6.8,85000,Action
3,3,Christopher Nolan,164.0,22000.0,27000.0,448130642.0,Tom Hardy,The Dark Knight Rises,0.0,deception|imprisonment|lawlessness|police offi...,English,PG-13,250000000.0,2012.0,8.5,164000,Action
4,4,Doug Walker,NaN,131.0,131.0,NaN,Doug Walker,Star Wars: Episode VII - The Force Awakens,0.0,NaN,NaN,NaN,NaN,NaN,7.1,0,Documentary

In [ ]:
df['kml']=df['mpg'] * 1.6/3.78
df.head()

KeyError: 'mpg'

In [ ]:
df['origin'].unique()

KeyError: 'origin'

In [ ]:
df['origin'].value_counts()

KeyError: 'origin'

In [ ]:
df.loc[3:15,: ]

,Unnamed: 0,director_name,duration,director_facebook_likes,actor_1_facebook_likes,gross,actor_1_name,movie_title,facenumber_in_poster,plot_keywords,language,content_rating,budget,title_year,imdb_score,movie_facebook_likes,genre
3,3,Christopher Nolan,164.0,22000.0,27000.0,448130642.0,Tom Hardy,The Dark Knight Rises,0.0,deception|imprisonment|lawlessness|police offi...,English,PG-13,250000000.0,2012.0,8.5,164000,Action
4,4,Doug Walker,NaN,131.0,131.0,NaN,Doug Walker,Star Wars: Episode VII - The Force Awakens,0.0,NaN,NaN,NaN,NaN,NaN,7.1,0,Documentary
5,5,Andrew Stanton,132.0,475.0,640.0,73058679.0,Daryl Sabara,John Carter,1.0,alien|american civil war|male nipple|mars|prin...,English,PG-13,263700000.0,2012.0,6.6,24000,Action
6,6,Sam Raimi,156.0,0.0,24000.0,336530303.0,J.K. Simmons,Spider-Man 3,0.0,sandman|spider man|symbiote|venom|villain,English,PG-13,258000000.0,2007.0,6.2,0,Action
7,7,Nathan Greno,100.0,15.0,799.0,200807262.0,Brad Garrett,Tangled,1.0,17th century|based on fairy tale|disney|flower...,English,PG,260000000.0,2010.0,7.8,29000,Adventure
8,8,Joss Whedon,141.0,0.0,26000.0,458991599.0,Chris Hemsworth,Avengers: Age of Ultron,4.0,artificial intelligence|based on comic book|ca...,English,PG-13,250000000.0,2015.0,7.5,118000,Action
9,9,David Yates,153.0,282.0,25000.0,301956980.0,Alan Rickman,Harry Potter and the Half-Blood Prince,3.0,blood|book|love|potion|professor,English,PG,250000000.0,2009.0,7.5,10000,Adventure
10,10,Zack Snyder,183.0,0.0,15000.0,330249062.0,Henry Cavill,Batman v Superman: Dawn of Justice,0.0,based on comic book|batman|sequel to a reboot|...,English,PG-13,250000000.0,2016.0,6.9,197000,Action
11,11,Bryan Singer,169.0,0.0,18000.0,200069408.0,Kevin Spacey,Superman Returns,0.0,crystal|epic|lex luthor|lois lane|return to earth,English,PG-13,209000000.0,2006.0,6.1,0,Action
12,12,Marc Forster,106.0,395.0,451.0,168368427.0,Giancarlo Giannini,Quantum of Solace,1.0,action hero|attempted rape|bond girl|official ...,English,PG-13,200000000.0,2008.0,6.7,0,Action
13,13,Gore Verbinski,151.0,563.0,40000.0,423032628.0,Johnny Depp,Pirates of the Caribbean: Dead Man's Chest,2.0,box office hit|giant squid|heart|liar's dice|m...,English,PG-13,225000000.0,2006.0,7.3,5000,Action
14,14,Gore Verbinski,150.0,563.0,40000.0,89289910.0,Johnny Depp,The Lone Ranger,1.0,horse|outlaw|texas|texas ranger|train,English,PG-13,215000000.0,2013.0,6.5,48000,Action
15,15,Zack Snyder,143.0,0.0,15000.0,291021565.0,Henry Cavill,Man of Steel,0.0,based on comic book|british actor playing amer...,English,PG-13,225000000.0,2013.0,7.2,118000,Action

In [ ]:
df['mpg'].hist()

KeyError: 'mpg'

In [ ]:
df_grouped=df['mpg'].groupby(df['origin'])
df_grouped.mean()

origin
europe    27.891429
japan     30.450633
usa       20.083534
Name: mpg, dtype: float64

In [ ]:
df.loc[df['mpg']>20,['name', 'mpg']]

                             name   mpg
14          toyota corona mark ii  24.0
15                plymouth duster  22.0
17                  ford maverick  21.0
18                   datsun pl510  27.0
19   volkswagen 1131 deluxe sedan  26.0
..                            ...   ...
393               ford mustang gl  27.0
394                     vw pickup  44.0
395                 dodge rampage  32.0
396                   ford ranger  28.0
397                    chevy s-10  31.0

[238 rows x 2 columns]

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/csv data/movies_imdb.csv")
df.head()

,Unnamed: 0,director_name,duration,director_facebook_likes,actor_1_facebook_likes,gross,actor_1_name,movie_title,facenumber_in_poster,plot_keywords,language,content_rating,budget,title_year,imdb_score,movie_facebook_likes,genre
0,0,James Cameron,178.0,0.0,1000.0,760505847.0,CCH Pounder,Avatar,0.0,avatar|future|marine|native|paraplegic,English,PG-13,237000000.0,2009.0,7.9,33000,Action
1,1,Gore Verbinski,169.0,563.0,40000.0,309404152.0,Johnny Depp,Pirates of the Caribbean: At World's End,0.0,goddess|marriage ceremony|marriage proposal|pi...,English,PG-13,300000000.0,2007.0,7.1,0,Action
2,2,Sam Mendes,148.0,0.0,11000.0,200074175.0,Christoph Waltz,Spectre,1.0,bomb|espionage|sequel|spy|terrorist,English,PG-13,245000000.0,2015.0,6.8,85000,Action
3,3,Christopher Nolan,164.0,22000.0,27000.0,448130642.0,Tom Hardy,The Dark Knight Rises,0.0,deception|imprisonment|lawlessness|police offi...,English,PG-13,250000000.0,2012.0,8.5,164000,Action
4,4,Doug Walker,NaN,131.0,131.0,NaN,Doug Walker,Star Wars: Episode VII - The Force Awakens,0.0,NaN,NaN,NaN,NaN,NaN,7.1,0,Documentary

Show the director, title and duration for the first 20 movies

In [ ]:
df.describe()

,Unnamed: 0,duration,director_facebook_likes,actor_1_facebook_likes,gross,facenumber_in_poster,budget,title_year,imdb_score,movie_facebook_likes
count,4916.000000,4901.000000,4814.000000,4909.000000,4.054000e+03,4903.000000,4.432000e+03,4810.000000,4916.000000,4916.000000
mean,2457.500000,107.090798,691.014541,6494.488491,4.764451e+07,1.377320,3.654749e+07,2002.447609,6.437429,7348.294142
std,1419.271292,25.286015,2832.954125,15106.986884,6.737255e+07,2.023826,1.002427e+08,12.453977,1.127802,19206.016458
min,0.000000,7.000000,0.000000,0.000000,1.620000e+02,0.000000,2.180000e+02,1916.000000,1.600000,0.000000
25%,1228.750000,93.000000,7.000000,607.000000,5.019656e+06,0.000000,6.000000e+06,1999.000000,5.800000,0.000000
50%,2457.500000,103.000000,48.000000,982.000000,2.504396e+07,1.000000,1.985000e+07,2005.000000,6.600000,159.000000
75%,3686.250000,118.000000,189.750000,11000.000000,6.110841e+07,2.000000,4.300000e+07,2011.000000,7.200000,2000.000000
max,4915.000000,511.000000,23000.000000,640000.000000,7.605058e+08,43.000000,4.200000e+09,2016.000000,9.500000,349000.000000

In [ ]:
df.loc[:20, ['director_name','duration','movie_title']]

        director_name  duration                                  movie_title
0       James Cameron     178.0                                       Avatar
1      Gore Verbinski     169.0     Pirates of the Caribbean: At World's End
2          Sam Mendes     148.0                                      Spectre
3   Christopher Nolan     164.0                        The Dark Knight Rises
4         Doug Walker       NaN   Star Wars: Episode VII - The Force Awakens
5      Andrew Stanton     132.0                                  John Carter
6           Sam Raimi     156.0                                 Spider-Man 3
7        Nathan Greno     100.0                                      Tangled
8         Joss Whedon     141.0                      Avengers: Age of Ultron
9         David Yates     153.0       Harry Potter and the Half-Blood Prince
10        Zack Snyder     183.0           Batman v Superman: Dawn of Justice
11       Bryan Singer     169.0                             Superman Returns
12       Marc Forster     106.0                            Quantum of Solace
13     Gore Verbinski     151.0   Pirates of the Caribbean: Dead Man's Chest
14     Gore Verbinski     150.0                              The Lone Ranger
15        Zack Snyder     143.0                                 Man of Steel
16     Andrew Adamson     150.0     The Chronicles of Narnia: Prince Caspian
17        Joss Whedon     173.0                                 The Avengers
18       Rob Marshall     136.0  Pirates of the Caribbean: On Stranger Tides
19   Barry Sonnenfeld     106.0                               Men in Black 3
20      Peter Jackson     164.0    The Hobbit: The Battle of the Five Armies

In [ ]:
new_df=df[df.director_name=="James Cameron"]
new_df.loc[:, ['gross', 'movie_title','title_year']]

            gross                 movie_title  title_year
0     760505847.0                      Avatar      2009.0
26    658672302.0                     Titanic      1997.0
285   204843350.0  Terminator 2: Judgment Day      1991.0
288   146282411.0                   True Lies      1994.0
599    54222000.0                   The Abyss      1989.0
2455   85200000.0                      Aliens      1986.0
3508   38400000.0              The Terminator      1984.0

Show the total gross sales for movies directed by the speified director

In [ ]:
print(new_df['gross'].sum())

1948125910.0

Compute the average movie length by genre(use groupby)

In [ ]:
genre_df=df.groupby('genre')
genre_df['duration'].mean()

genre
Action         110.676577
Adventure      106.482916
Animation       82.229508
Biography      125.412000
Comedy          99.498090
Crime          112.032544
Documentary     93.204819
Drama          113.164544
Family          96.454545
Fantasy        101.042553
Film-Noir       95.000000
Game-Show       60.000000
History         90.000000
Horror          96.574661
Music           93.000000
Musical        103.750000
Mystery        107.531250
Romance         85.500000
Sci-Fi         100.076923
Thriller       103.666667
Western        106.000000
Name: duration, dtype: float64

In [ ]:
genre_df=df.groupby('genre')
df.sort_values('duration')

,Unnamed: 0,director_name,duration,director_facebook_likes,actor_1_facebook_likes,gross,actor_1_name,movie_title,facenumber_in_poster,plot_keywords,language,content_rating,budget,title_year,imdb_score,movie_facebook_likes,genre
1930,1930,NaN,7.0,NaN,45.0,NaN,Justin Fletcher,Shaun the Sheep,0.0,farmer|mischief|no dialog|sheep|sheepdog,English,TV-G,NaN,NaN,8.3,834,Animation
2316,2316,Jane Clark,7.0,23.0,344.0,NaN,Necar Zadegan,The Touch,0.0,lesbian|paris france|period piece|poem|poetess,English,NaN,13000.0,2007.0,5.2,30,Romance
3997,3997,NaN,11.0,NaN,11.0,NaN,Matthew Senreich,Robot Chicken,0.0,celebrity|robot|satire|sketch comedy|stop moti...,English,TV-MA,NaN,NaN,7.8,1000,Animation
4564,4564,Clark Baker,14.0,0.0,134.0,NaN,Taylor Pigeon,Vessel,1.0,alien|flight attendant|monster|pilot|tentacle,English,NaN,NaN,2012.0,6.2,14,Horror
4342,4342,Robert Greenwald,20.0,21.0,0.0,NaN,Lee Scott,Wal-Mart: The High Cost of Low Price,0.0,greed|pollution|slave labor|truth|wal mart,English,Not Rated,1500000.0,2005.0,6.8,0,Documentary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4416,4416,NaN,NaN,NaN,511.0,NaN,Richard Cawthorne,Wolf Creek,0.0,based on true story|blood|serial killer|slashe...,English,NaN,NaN,NaN,7.1,954,Drama
4502,4502,Wajahat Rauf,NaN,3.0,7.0,NaN,Rasheed Naz,Karachi se Lahore,9.0,pakistan|road trip,Urdu,NaN,1000000.0,2015.0,7.0,259,Comedy
4580,4580,Joseph Kosinski,NaN,364.0,22000.0,NaN,Peter Dinklage,Destiny,0.0,first person shooter,English,NaN,NaN,2014.0,8.1,1000,Action
4825,4825,Valentine,NaN,0.0,17.0,NaN,Diane Sorrentino,Romantic Schemer,2.0,NaN,English,PG-13,125000.0,2015.0,5.1,0,Romance
4863,4863,Daniel Mellitz,NaN,0.0,1000.0,NaN,Corbin Bernsen,The Naked Ape,0.0,coming of age|male nudity|road trip|skinny dip...,English,NaN,NaN,2006.0,4.7,2,Comedy